### ISSUE TITLE
Update minify github action

### ISSUE THREAD

**Issue by alexmigf** [wpovernight/woocommerce-pdf-invoices-packing-slips#225]
Following the discovery by @Spreeuw that `pull_request` requires paths and some tests we made, we concluded that it's better to use only push:

```yml
on:
  workflow_dispatch:
  push:
    paths: 
      - 'assets/**/*.js'
      - 'assets/**/*.css'
```
